import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase";
import { validateAdminSession, logAdminAction } from "@/lib/admin-auth";
import { generateLicenseKey, hashLicenseKey } from "@/lib/license";

export async function POST(req: NextRequest) {
  const token = req.cookies.get("prowler_admin_token")?.value;
  if (!token) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  const admin = await validateAdminSession(token);
  if (!admin) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { plan, duration, devices, email, notes } = await req.json();

    if (!["basic", "pro", "elite"].includes(plan)) {
      return NextResponse.json({ error: "Invalid plan" }, { status: 400 });
    }

    const key = generateLicenseKey();
    const keyHash = hashLicenseKey(key, process.env.MASTER_SECRET!);

    const expiresAt =
      duration === "lifetime"
        ? null
        : new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString();

    const { data: license, error: licenseError } = await supabaseAdmin
      .from("licenses")
      .insert({
        key_hash: keyHash,
        plan,
        status: "active",
        email: email || null,
        plan_duration: duration,
        max_machines: devices === "unlimited" ? 999 : 1,
        expires_at: expiresAt,
        notes: notes || `Manual — Generated by ${admin.email}`,
      })
      .select()
      .single();

    if (licenseError) {
      throw new Error("Failed to create license");
    }

    await logAdminAction(
      admin.email,
      "generated_license",
      "license",
      license.id,
      { plan, duration, devices, email }
    );

    return NextResponse.json({
      success: true,
      key,
      licenseId: license.id,
    });
  } catch (err) {
    console.error("Generate license error:", err);
    return NextResponse.json(
      { error: "Failed to generate license" },
      { status: 500 }
    );
  }
}